services:
  # Database initialization service
  service-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        POSTGRES_UID: ${POSTGRES_UID:-1100}
        POSTGRES_GID: ${POSTGRES_GID:-1100}
    container_name: service-init
    volumes:
      - /tmp/${SERVICE_NAME}/data:/var/lib/postgresql/17/main
    environment:
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=${SERVICE_NAME}
      - DB_ACTION=${DB_ACTION:-init}
    command: [ "/opt/service/scripts/init-db.sh" ]
    profiles:
      - init

  # Main development service
  service-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        POSTGRES_UID: ${POSTGRES_UID:-1100}
        POSTGRES_GID: ${POSTGRES_GID:-1100}
    container_name: service-dev
    ports:
      - "50001:50001"
      - "5432:5432"
    volumes:
      - ../external/$(SERVICE_NAME):/opt/service/src
      - /tmp/${SERVICE_NAME}/data:/var/lib/postgresql/17/main
      - /tmp/${SERVICE_NAME}/logs/postgresql:/var/log/postgresql
    environment:
      - RUST_LOG=debug
      - DATABASE_URL=postgres://db_user:dev_password@localhost:5432/${SERVICE_NAME}
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
    restart: unless-stopped

  # Test service
  service-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        POSTGRES_UID: ${POSTGRES_UID:-1100}
        POSTGRES_GID: ${POSTGRES_GID:-1100}
    container_name: service-test
    volumes:
      - ../external/$(SERVICE_NAME):/opt/service/src
      - /tmp/${SERVICE_NAME}/logs/test:/tmp/service/logs/test
    environment:
      - POSTGRES_DATA_DIR=/var/lib/postgresql/17/main
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=${SERVICE_NAME}_test
      - DATABASE_URL=postgres://db_user:test_password@localhost:5432/${SERVICE_NAME}_test
      - RUST_LOG=debug
      - RUST_BACKTRACE=${RUST_BACKTRACE:-0}
      - TEST_FILES=${TEST_FILES:-}
    command: [ "/opt/service/scripts/test.sh" ]
    profiles:
      - test

volumes:
  postgres_data:
    driver: local
